import * as dotenv from "dotenv";
dotenv.config();
export enum NETWORK {
  POLYGON,
  HARDHAT,
}
enum VOUCHER_TOKENS {
  TOKEN_1 = 1,
  TOKEN_2 = 2,
  TOKEN_3 = 3,
  TOKEN_4 = 4,
}

const config = {
  CREDENTIALS: {
    [NETWORK.HARDHAT]: {
      PRIVATE_KEY: process.env.PRIVATE_KEY_DEV,
      ACCOUNT_ADDRESS: process.env.DEEWARR_ACCOUNT_DEV,
      NFT_CONTRACT_ADDRESS: process.env.NFT_CONTRACT_ADDRESS_DEV,
      SOULBOUNT_CONTRACT_ADDRESS: process.env.SOULBOUND_CONTRACT_ADDRESS_DEV,
    },
    [NETWORK.POLYGON]: {
      PRIVATE_KEY: process.env.PRIVATE_KEY,
      ACCOUNT_ADDRESS: process.env.DEEWARR_ACCOUNT,
      NFT_CONTRACT_ADDRESS: process.env.NFT_CONTRACT_ADDRESS,
      SOULBOUNT_CONTRACT_ADDRESS: process.env.SOULBOUND_CONTRACT_ADDRESS,
    },
  },
  CURRENT_NETWORK: NETWORK.POLYGON,
  VOUCHER_VALUES: {
    [VOUCHER_TOKENS.TOKEN_1]: 10,
    [VOUCHER_TOKENS.TOKEN_2]: 20,
    [VOUCHER_TOKENS.TOKEN_3]: 30,
    [VOUCHER_TOKENS.TOKEN_4]: 40,
  },
};
export default config;
